#!/usr/bin/env node
/**
 * Master test runner for elm-lsp-rust
 * Runs all test suites and updates coverage documentation
 */

import { spawn } from "child_process";
import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const GREEN = "\x1b[32m";
const RED = "\x1b[31m";
const YELLOW = "\x1b[33m";
const CYAN = "\x1b[36m";
const RESET = "\x1b[0m";
const BOLD = "\x1b[1m";

function runTest(scriptPath, name) {
  return new Promise((resolve) => {
    const child = spawn("node", [scriptPath], {
      stdio: ["inherit", "pipe", "pipe"],
      cwd: dirname(scriptPath),
    });

    let stdout = "";
    let stderr = "";

    child.stdout.on("data", (data) => {
      const text = data.toString();
      stdout += text;
      process.stdout.write(text);
    });

    child.stderr.on("data", (data) => {
      const text = data.toString();
      stderr += text;
      process.stderr.write(text);
    });

    child.on("close", (code) => {
      // Parse results from output
      const passMatch = stdout.match(/Passed:\s*(\d+)/);
      const failMatch = stdout.match(/Failed:\s*(\d+)/);

      resolve({
        name,
        exitCode: code,
        passed: passMatch ? parseInt(passMatch[1]) : 0,
        failed: failMatch ? parseInt(failMatch[1]) : 0,
        output: stdout,
      });
    });

    child.on("error", (err) => {
      resolve({
        name,
        exitCode: 1,
        passed: 0,
        failed: 1,
        output: err.message,
      });
    });
  });
}

function parseCoverageFromOutput(output) {
  const match = output.match(/__COVERAGE_JSON_START__\s*([\s\S]*?)\s*__COVERAGE_JSON_END__/);
  if (match) {
    try {
      return JSON.parse(match[1]);
    } catch (e) {
      console.error("Failed to parse coverage JSON:", e.message);
    }
  }
  return null;
}

function generateCoverageFile(fixtureResults, meetdownResults, fixtureCoverage, meetdownCoverage) {
  const now = new Date().toISOString().split("T")[0];
  const totalPassed = fixtureResults.passed + meetdownResults.passed;
  const totalFailed = fixtureResults.failed + meetdownResults.failed;
  const totalTests = totalPassed + totalFailed;

  // Aggregate tool usage counts
  const toolStats = {};
  const allTools = [
    "elm_completion", "elm_hover", "elm_definition", "elm_references",
    "elm_symbols", "elm_format", "elm_diagnostics", "elm_code_actions",
    "elm_apply_code_action",
    "elm_rename_function", "elm_rename_type", "elm_rename_variant", "elm_rename_field",
    "elm_move_function", "elm_prepare_remove_variant", "elm_remove_variant",
    "elm_rename_file", "elm_move_file"
  ];

  // Initialize all tools with 0 counts
  for (const tool of allTools) {
    toolStats[tool] = { fixture: 0, meetdown: 0 };
  }

  // Count fixture tests per tool
  if (fixtureCoverage?.coverage) {
    for (const [testName, tools] of Object.entries(fixtureCoverage.coverage)) {
      for (const tool of tools) {
        if (toolStats[tool]) {
          toolStats[tool].fixture++;
        }
      }
    }
  }

  // Count meetdown tests per tool
  if (meetdownCoverage?.coverage) {
    for (const [testName, tools] of Object.entries(meetdownCoverage.coverage)) {
      for (const tool of tools) {
        if (toolStats[tool]) {
          toolStats[tool].meetdown++;
        }
      }
    }
  }

  // Generate markdown content
  let content = `# Test Coverage Mapping

This document maps all MCP tools (features) to their corresponding tests.
**This file is auto-generated by \`run_all_tests.mjs\` - do not edit manually.**

## Feature Coverage Summary

| Feature | Fixture Tests | Meetdown Tests | Coverage |
|---------|---------------|----------------|----------|
`;

  for (const tool of allTools) {
    const stats = toolStats[tool];
    const total = stats.fixture + stats.meetdown;
    let status;
    if (total === 0) {
      status = "❌ None";
    } else if (total >= 4) {
      status = "✅ Excellent";
    } else if (total >= 2) {
      status = "✅ Good";
    } else {
      status = "⚠️ Basic";
    }
    content += `| ${tool} | ${stats.fixture} | ${stats.meetdown} | ${status} |\n`;
  }

  content += `
**Legend:**
- ✅ Excellent: 4+ test cases with comprehensive coverage
- ✅ Good: 2-3 tests covering different scenarios
- ⚠️ Basic: Only 1 test, needs more coverage
- ❌ None: No tests exist

---

## All Tests (${totalTests} total)

### Fixture Tests (${fixtureResults.passed} tests)

`;

  // List fixture tests
  if (fixtureCoverage?.coverage) {
    const fixtureTests = Object.keys(fixtureCoverage.coverage).sort();
    for (const testName of fixtureTests) {
      const tools = fixtureCoverage.coverage[testName];
      content += `- **${testName}** → ${tools.join(", ")}\n`;
    }
  }

  content += `
### Meetdown Tests (${meetdownResults.passed} tests)

`;

  // List meetdown tests
  if (meetdownCoverage?.coverage) {
    const meetdownTests = Object.keys(meetdownCoverage.coverage).sort((a, b) => {
      // Sort by test number
      const numA = parseInt(a.match(/Test (\d+)/)?.[1] || "0");
      const numB = parseInt(b.match(/Test (\d+)/)?.[1] || "0");
      return numA - numB;
    });
    for (const testName of meetdownTests) {
      const tools = meetdownCoverage.coverage[testName];
      content += `- **${testName}** → ${tools.join(", ")}\n`;
    }
  }

  content += `
---

## Test Execution

\`\`\`bash
# Run fixture tests (${fixtureResults.passed} tests)
node tests/run_tests.mjs

# Run meetdown real-world tests (${meetdownResults.passed} tests)
node tests/test_meetdown_comprehensive.mjs

# Run all tests
node tests/run_all_tests.mjs
\`\`\`

---

`;

  const statusLine = totalFailed === 0
    ? `*Last updated: ${now} - All ${totalTests} tests passing ✅*`
    : `*Last updated: ${now} - ${totalPassed}/${totalTests} tests passing (${totalFailed} failed) ⚠️*`;

  content += statusLine + "\n";

  writeFileSync(join(__dirname, "COVERAGE.md"), content);
}

async function main() {
  console.log(`\n${BOLD}${"=".repeat(70)}${RESET}`);
  console.log(`${BOLD}  elm-lsp-rust Master Test Suite${RESET}`);
  console.log(`${BOLD}${"=".repeat(70)}${RESET}\n`);

  const fixtureTestPath = join(__dirname, "run_tests.mjs");
  const meetdownTestPath = join(__dirname, "test_meetdown_comprehensive.mjs");

  // Run fixture tests
  console.log(`${CYAN}Running fixture tests...${RESET}\n`);
  const fixtureResults = await runTest(fixtureTestPath, "Fixture Tests");
  const fixtureCoverage = parseCoverageFromOutput(fixtureResults.output);

  console.log(`\n${CYAN}Running meetdown comprehensive tests...${RESET}\n`);
  const meetdownResults = await runTest(meetdownTestPath, "Meetdown Tests");
  const meetdownCoverage = parseCoverageFromOutput(meetdownResults.output);

  // Generate coverage file from test data
  generateCoverageFile(fixtureResults, meetdownResults, fixtureCoverage, meetdownCoverage);

  // Final summary
  const totalPassed = fixtureResults.passed + meetdownResults.passed;
  const totalFailed = fixtureResults.failed + meetdownResults.failed;

  console.log(`\n${BOLD}${"=".repeat(70)}${RESET}`);
  console.log(`${BOLD}  Master Test Summary${RESET}`);
  console.log(`${BOLD}${"=".repeat(70)}${RESET}`);
  console.log(`\n  ${BOLD}Fixture Tests:${RESET}`);
  console.log(`    ${GREEN}Passed: ${fixtureResults.passed}${RESET}`);
  console.log(`    ${fixtureResults.failed > 0 ? RED : GREEN}Failed: ${fixtureResults.failed}${RESET}`);

  console.log(`\n  ${BOLD}Meetdown Tests:${RESET}`);
  console.log(`    ${GREEN}Passed: ${meetdownResults.passed}${RESET}`);
  console.log(`    ${meetdownResults.failed > 0 ? RED : GREEN}Failed: ${meetdownResults.failed}${RESET}`);

  console.log(`\n  ${BOLD}Total:${RESET}`);
  console.log(`    ${GREEN}Passed: ${totalPassed}${RESET}`);
  console.log(`    ${totalFailed > 0 ? RED : GREEN}Failed: ${totalFailed}${RESET}`);
  console.log(`    Tests:  ${totalPassed + totalFailed}`);

  if (totalFailed > 0) {
    console.log(`\n${RED}${"=".repeat(70)}${RESET}`);
    console.log(`${RED}  TESTS FAILED${RESET}`);
    console.log(`${RED}${"=".repeat(70)}${RESET}\n`);
    process.exit(1);
  } else {
    console.log(`\n${GREEN}${"=".repeat(70)}${RESET}`);
    console.log(`${GREEN}  ALL TESTS PASSED${RESET}`);
    console.log(`${GREEN}${"=".repeat(70)}${RESET}\n`);
    process.exit(0);
  }
}

main().catch((err) => {
  console.error(`${RED}Fatal error: ${err.message}${RESET}`);
  process.exit(1);
});
